name: Test and deploy user.yaml files

on:
  workflow_call:
    inputs:
      BUCKET:
        required: true
        type: string
      REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  ci:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install gen3users
        pip install pyyaml==5.4
    - name: Lint files
      run: |
        cat - > lint.py <<EOM
        import os
        import yaml

        def lint():
            for commons in os.listdir("./users"):
                with open(os.path.join("users", commons, "user.yaml"), "r") as f:
                    data = yaml.safe_load(f)
                # pyyaml auto sort
                with open(os.path.join("users", commons, "user.yaml"), "w") as f:
                    yaml.dump(data, f)

        lint()
        EOM
        python lint.py
        rm lint.py
    - name: Run tests
      run: gen3users validate users/*/user.yaml
    - name: Install AWS CLI
      if: github.ref == 'refs/heads/master'
      uses: chrislennon/action-aws-cli@1.1
    - name: Deploy to S3
      if: github.ref == 'refs/heads/master'
      run: aws s3 cp users s3://${{ inputs.BUCKET }}/ --recursive --region ${{ inputs.REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
