name: Test and deploy dictionaries

on:
  workflow_call:
    inputs:
      BUCKET:
        required: false
        type: string
        default: "dictionary-artifacts"
      REGION:
        required: false
        type: string
        default: "us-east-1"
      DIRECTORY:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6.9'
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true
    - name: Install AWS CLI
      uses: chrislennon/action-aws-cli@1.1
    - name: Initialize Packages
      run: |
        yes | python setup.py install
        git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
        ./run_tests.sh
        aws s3 cp artifacts s3://${{ inputs.BUCKET }}/${{ inputs.DIRECTORY }}/$GITHUB_REF_NAME --recursive --region ${{ inputs.REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
