---
name: Lint
on: [workflow_call]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          # this is uploaded by the lint-create-config.yaml workflow
          name: linters-config
          path: .github/linters

      - name: Display structure of downloaded linters-config files
        run: ls -aR
        working-directory: .github/linters

      - uses: actions/download-artifact@v3
        with:
          # this is uploaded by the lint-create-config.yaml workflow
          name: super-linter-config
          path: .github/

      - name: Display structure of downloaded super-linter-config file
        run: ls -aR
        working-directory: .github

      - name: Lint Repo
        uses: github/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "/linters"
