name: Node.js CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.repository != 'uc-cdis/data-portal' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        working-directory: ./src
      - run: npm test

  build2:

    runs-on: ubuntu-latest
    if: ${{ github.repository == 'uc-cdis/data-portal' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        working-directory: ./src
      - run: npm relay
      - run: npm params
      - run: npm test
      - name: check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "testSchema.sh"
          if: ${{ steps.check_files.outputs.files_exists == 'true' }}
          run: |
            - ./testSchema.sh
