# github action set up NPM with input version, and run npm install, then run npm test, then run codecov and upload coverage report to codecov.io
name: NPM Unit Test
on:
  workflow_call:
    inputs:
      node-version:
          required: false
          type: string
          default: "16"
      NPM_VERSION:
        description: 'The NPM version to use for this job'
        required: false
        type: string
        default: "8.5"

jobs:
  unit_test:
    name: NPM Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.NPM_VERSION }}

      - name: NPM CI
        run: |
          npm install -g npm && npm ci
          npm run test
