name: Node.js CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        type: string
      npm-version:
        description: 'NPM version'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.repository != 'uc-cdis/data-portal' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run build --if-present
        working-directory: ./src
      - run: npm test

  build data portal:

    runs-on: ubuntu-latest
    if: ${{ github.repository == 'uc-cdis/data-portal' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm install -g npm@${{ inputs.npm-version }}
      - run: npm ci
      - run: npm run build --if-present
        working-directory: ./src
      - run: npm run relay
      - run: npm run params
      - run: npm test
      - run: |
          bash ${GITHUB_WORKSPACE}/testSchema.sh
