name: "PyPI Poetry Publish"

# This expects tags to be available and assumes that the main branch is either
# named `main` or `master`
#
# you can use this in a GH Action like this:
#
#  name: PyPI
#  on:
#    push:
#      branches:
#        - main
#        - master
#      tags:
#        - '*'
#  jobs:
#    PyPIPoetryPublish:
#      name: PyPI Poetry Publish
#      uses: uc-cdis/.github/.github/workflows/python_package_index_publish.yaml@feat/pypi
#      with:
#          PYTHON_VERSION: '3.9'
#          IS_TEST_PUBLISH: false
#      secrets:
#        PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
#        PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
#
#
# For using Test PyPI, you can have another GH Action that uses the same template
# but runs on all branches:
#
#  name: PyPI Test
#  on:
#    push:
#      branches:
#        - '*'
#      tags:
#        - '*'
#  jobs:
#    PyPIPoetryPublish:
#      name: PyPI Poetry Publish
#      uses: uc-cdis/.github/.github/workflows/python_package_index_publish.yaml@feat/pypi
#      with:
#          PYTHON_VERSION: '3.9'
#          IS_TEST_PUBLISH: true
#      secrets:
#        PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
#        PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        description: 'The Python version to use'
        required: false
        default: '3.9'
        type: string
      IS_TEST_PUBLISH:
        description: 'Whether or not to test publishing to Test PyPI on non-real releases'
        required: true
        default: true
        type: boolean
    secrets:
      PYPI_TEST_API_TOKEN:
        required: true
      PYPI_PROD_API_TOKEN:
        required: true
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install poetry
        # that is poetry's recommended way to install
        run: |
          pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          pip list
          poetry show

      - name: Install dependencies
        run: |
          poetry install -vv --all-extras --no-interaction --no-cache
          poetry show -vv
        shell: bash

      - name: Configure PyPI Repos in Poetry and Poetry Build
        env:
          PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
          PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $PYPI_TEST_API_TOKEN
          poetry config pypi-token.pypi $PYPI_PROD_API_TOKEN
          poetry build
        shell: bash

      - name: Publish to Test PyPI
        if: inputs.IS_TEST_PUBLISH && !contains(github.ref, 'refs/heads/main') && !contains(github.ref, 'refs/heads/master') && !startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Since this is not a tagged release on the main branch, do a test publish"
          poetry publish -n -vv -r testpypi

      - name: Publish to PyPI
        if: (contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/master')) && startsWith(github.ref, 'refs/tags/') && !inputs.IS_TEST_PUBLISH
        run: |
          echo "Since this is a tagged release on the main branch, do a real publish"
          poetry publish -n -vv
