name: "PyPI Poetry Publish"

# This expects tags to be available and assumes that the main branch is either
# named `main` or `master`
#
# you can use this in a GH Action like this:
#
#  name: PyPI
#  on:
#    push:
#      tags:
#        - '*'
#  jobs:
#    PyPIPoetryPublish:
#      name: PyPI Poetry Publish
#      uses: uc-cdis/.github/.github/workflows/python_package_index_publish.yaml@master
#      with:
#          PYTHON_VERSION: '3.9'
#          DO_TEST_PUBLISH_FIRST: true
#      secrets:
#        PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
#        PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
#
on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        description: 'The Python version to use'
        required: false
        default: '3.9'
        type: string
      DO_TEST_PUBLISH_FIRST:
        description: 'Whether or not to test publishing to Test PyPI first'
        required: true
        default: true
        type: boolean
      TEST_PYPI_PACKAGE_NAME:
        description: 'Overrides official name to avoid name conflicts in Test PyPI'
        required: false
        type: string
    secrets:
      PYPI_TEST_API_TOKEN:
        required: false
      PYPI_PROD_API_TOKEN:
        required: true
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install poetry
        # that is poetry's recommended way to install
        run: |
          pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          pip list
          poetry show
      - name: Install dependencies
        run: |
          poetry install -vv --all-extras --no-interaction --no-cache
          poetry show -vv
        shell: bash

      - name: Configure Test PyPI Repo
        if: ${{ inputs.DO_TEST_PUBLISH_FIRST }}
        env:
          PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
        run: |
          poetry config pypi-token.testpypi $PYPI_TEST_API_TOKEN
        shell: bash

      - name: Configure Prod PyPI Repo and Poetry Build
        env:
          PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.pypi $PYPI_PROD_API_TOKEN
          poetry build
        shell: bash

      - name: Getting information
        run: |
          echo github.ref=${{ github.ref }}
        shell: bash

      - name: Rename and rebuild for Test PyPI
        id: rename-test-pypi
        if: ${{ inputs.TEST_PYPI_PACKAGE_NAME && inputs.DO_TEST_PUBLISH_FIRST && startsWith(github.ref, 'refs/tags/') }}
        run: |

          echo "Backing up original pyproject.toml"
          cp pyproject.toml pyproject.toml.orig

          echo "Renaming package to: ${{ inputs.TEST_PYPI_PACKAGE_NAME }}"
          # Replace the [tool.poetry] name safely (line starts with 'name = "..."')
          sed -i.bak -E 's/^name\s*=\s*".*"/name = "'"${{ inputs.TEST_PYPI_PACKAGE_NAME }}"'"/' pyproject.toml

          echo "New name line:"
          grep -E '^name\s*=' pyproject.toml || true

          ORIGINAL_PACKAGE=$(grep '^name\s*=' pyproject.toml.orig | head -1 | sed "s/name *= ['\"]//;s/['\"]//")
          echo "Moving original source folder ${ORIGINAL_PACKAGE} to ${{ inputs.TEST_PYPI_PACKAGE_NAME }}"
          mv ${ORIGINAL_PACKAGE} ${{ inputs.TEST_PYPI_PACKAGE_NAME }}

          echo "Rebuilding dist for Test PyPI"
          rm -rf dist/*
          poetry build -n

      - name: Publish to Test PyPI
        id: test-pypi
        if: ${{ inputs.DO_TEST_PUBLISH_FIRST && startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Publishing to Test PyPI"
          poetry publish -n -vv -r testpypi

      - name: Restore name and rebuild for Real PyPI
        id: undo-rename-pypi
        env:
          PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
        if: ${{ inputs.TEST_PYPI_PACKAGE_NAME && inputs.DO_TEST_PUBLISH_FIRST && startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Restoring original pyproject.toml"
          mv -f pyproject.toml.orig pyproject.toml

          echo "Restored name line:"
          grep -E '^name\s*=' pyproject.toml || true

          ORIGINAL_PACKAGE=$(grep '^name\s*=' pyproject.toml | head -1 | sed "s/name *= ['\"]//;s/['\"]//")
          echo "Recovering original source folder ${ORIGINAL_PACKAGE} from ${{ inputs.TEST_PYPI_PACKAGE_NAME }}"
          mv ${{ inputs.TEST_PYPI_PACKAGE_NAME }} ${ORIGINAL_PACKAGE}

          echo "Rebuilding dist for Real PyPI"
          rm -rf dist/*
          poetry build -n
        shell: bash

      - name: Publish to PyPI
        id: prod-pypi
        if: ${{ (!inputs.DO_TEST_PUBLISH_FIRST || (inputs.DO_TEST_PUBLISH_FIRST && steps.test-pypi.outcome == 'success')) && startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Since this is a tagged release, do a real publish"
          poetry publish -n -vv

      - name: If Publish to PyPI Did Not Succeed, Fail Job
        if: ${{ steps.prod-pypi.outcome != 'success' }}
        run: |
          echo "Since this is a tagged release, and the real publish failed or didn't run, fail the job"
          exit 1
