---
name: Required Lint Checks
# this is intended to block on a limited set of required lint to remove
#
# The required lint check, is, well, required to pass and WILL block merges and builds,
# but is opinionated and slim (there are only a few things we error on).
#
on:
  workflow_call:
    inputs:
      poetry-version:
        description: 'The Poetry package manager version to use. Defaults to latest'
        required: false
        default: ''
        type: string
      python-version:
        description: 'The Python version to use and defaults to latest'
        required: false
        default: '3.13'
        type: string
      use-cache:
        required: false
        default: true
        type: boolean
jobs:
  post-commit:
    name: Post-Commit Validation of Pre-Commit Checks
    uses: uc-cdis/.github/.github/workflows/pre_commit.yaml@fix/linting

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout repo containing central linter config
        uses: actions/checkout@v5
        with:
          repository: uc-cdis/.github
          # TODO: Update
          ref: fix/linting
          persist-credentials: false
          path: uc-cdis/.github
          sparse-checkout: |
            .github/linters

      - name: Display files
        run: ls -aR uc-cdis/.github/.github/

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Display files
        run: ls -aR

      # cache the dependencies based on a hash of the lock file
      - name: Poetry cache
        if: inputs.use-cache
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install poetry
        # that is poetry's recommended way to install
        # Empty POETRY_VERSION will get latest
        run: |
          pip install --upgrade pip
          if [ -n "${{ inputs.poetry-version }}" ]; then
            curl -sSL https://install.python-poetry.org | POETRY_VERSION="${{ inputs.poetry-version }}" python -
          else
            curl -sSL https://install.python-poetry.org | python -
          fi
          pip list
          poetry install -vv --all-extras --no-interaction
          poetry show

      - name: Save poetry cache if cache miss
        if: inputs.use-cache && steps.cache-poetry.outputs.cache-hit != 'true'
        run: echo "Cache miss, saving the cache"

      - name: Update pylint config with Python module path
        working-directory: uc-cdis/.github/.github/linters
        run: bash update_pylint_config.sh

      - name: Cat file(s)
        working-directory: uc-cdis/.github/.github/linters
        run: cat .python-lint

      - name: Lint Repo
        run: pylint . --rcfile uc-cdis/.github/.github/linters/.python-lint
